version: '3'
services:
  api:
    build: .
    container_name: node_api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    networks:
      - app-network

  mongo:
    image: mongo:6.0.4-focal
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
