services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: "" #Add your db URI here
      REDIS_HOST: redis
      PORT: 3000
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo 
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

volumes:
  mongo_data:
