services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: mongodb+srv://passisadmin123:admin123@cluster0.iil4k.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      REDIS_HOST: redis
      PORT: 3000
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo  # Changed from mongo:alpine to mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

volumes:
  mongo_data:
